import { Outfit } from "next/font/google";
import { AuthProvider } from "./Provider";
import { JobProvider } from "@/context/JobContext";
import { Toaster } from "react-hot-toast";

import "./globals.css";

const outfit = Outfit({ subsets: ["latin"], weight: ["300", "400", "500"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-100">
      <body className={`${outfit.className} antialiased text-gray-700`}>
        <AuthProvider>
          <JobProvider>
            <Toaster />

            {children}
          </JobProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
